### ISSUE TITLE
Locally stored media

### ISSUE THREAD

**Issue by aubreywullschleger** [Manu010966/Colmar-Academy#2]
Great! Nice job using locally stored media for your project. This is best practice for production code and helps your page load faster. 

Example: https://github.com/Manu010966/Colmar-Academy/blob/master/index.html#L164

Also, wonderful job using descriptive `alt` attributes on your `<img>` elements. This is definitely best practice and helps make your site even more accessible!

**Comment by Manu010966** [comment]
Thanks!
