### ISSUE TITLE
Flex-box and media queries in CSS

### ISSUE THREAD

**Issue by aubreywullschleger** [Manu010966/Colmar-Academy#3]
Great! Awesome job with using flex-box and media queries for a totally responsive page. One thing to work on here would be using one media query for each media query width.  For example I'm seeing ten instances of `@media only screen and (max-width: 590px)`.  Instead you should only need one instance of `@media only screen and (max-width: 590px)` with all of your styles for that screen width inside the query.

**Comment by Manu010966** [comment]
I'll improve the css media. thaks for your advice
