### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by aubreywullschleger** [Manu010966/Colmar-Academy#4]
Grade: Meets expectations

Summary:
Overall, awesome work on this final project! I love your semantic HTML elements, your use of locally stored media, and that your page is totally responsive.

One thing to work on would be: making your CSS even more concise by using one media query for each screen width instead of multiple media queries for the same screen width.

Next, I challenge you to build more pages for this site.  What does a sign in page look like? What about a course page?  Building these extra pages will add some complexity and is a challenge I think you are ready for based on your great work here!

**Comment by Manu010966** [comment]
yeah you're right, now that you mention the use of media,    I realice of that 
thanks !
